Repository ivpn/ivpn.net, pull requests merged in 2021-06, with the labels that each got.

#179 RaspPi Privacy Guide: Fix link, fix company name, fix comment in iptables rules
  src/content/pages/privacy-guides/raspberry-pi-2-ivpn-gateway.md
Labels: type: documentation

#180 update dd-wrt wireguard documentation
  src/content/pages/knowledgebase/routers/dd-wrt-how-do-i-exclude-hosts-or-bypass-vpn-tunnel.md
  src/content/pages/knowledgebase/routers/how-to-enable-a-andsharp039kill-switchandsharp039-in-my-dd-wrtortomato-router.md
  src/content/pages/setup/router/ddwrt-wireguard.md
  src/static/images-static/uploads/install-openvpn-ddwrt-wireguard-020.png
Labels: type: documentation

#161 Upgrade dependencies
  Dockerfile
  src/static/images/icon-payment-dinersclub.svg
  src/static/images/icon-payment-discover.svg
  src/static/images/icon-payment-jcb.svg
  src/static/images/icon-payment-maestro.svg
  src/static/images/icon-payment-mastercard.svg
  src/static/images/icon-payment-unionpay.svg
  src/static/images/icon-payment-visa.svg
  src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
  src/themes/ivpn-v3/package.json
  src/themes/ivpn-v3/webpack.mix.js
  src/themes/ivpn-v3/yarn.lock
Labels: type: task

#169 Connection info browser cache issue
  src/themes/ivpn-v3/assets/js/menu.js
Labels: type: bug

#185 Handle Braintree "authentication_unavailable" error
  src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
Labels: type: bug

#187 Fix typo about WireGuard DNS IP address and clarify DNS IP availability.
  src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
Labels: type: documentation

#188 Fix missing bold for questions in WireGuard FAQ
  src/content/pages/knowledgebase/general/wireguard-faq.md
Labels: type: documentation

#191 Fixes #189 : update systemd unit file
  src/content/pages/knowledgebase/linux/managing-the-ivpn-linux-client-at-system-boot.md
Labels: type: documentation

#194 Upgrade dependencies
  src/themes/ivpn-v3/package.json
  src/themes/ivpn-v3/yarn.lock
Labels: type: build/ci

#197 New blog post
  src/content/blog/ipv6-over-ipv4-available-for-testing.md
Labels: type: task

#181 ipv6 documentation update
  src/content/pages/knowledgebase/general/do-you-offer-ipv6.md
  src/content/pages/knowledgebase/general/wireguard-faq.md
  src/content/pages/knowledgebase/linux/linux-how-do-i-prevent-vpn-leaks-using-iptables.md
  src/content/pages/knowledgebase/linux/linux-kill-switch-using-the-uncomplicated-firewall-ufw.md
  src/content/pages/knowledgebase/windows/windows-10-disable-ipv6.md
  src/content/pages/setup/linux-wireguard.md
  src/content/pages/setup/macos-wireguard.md
  src/content/pages/setup/router/ddwrt-wireguard.md
  src/content/pages/setup/router/opnsense.md
  src/content/pages/setup/router/pfsense-wireguard.md
  src/content/pages/setup/windows-10-wireguard.md
  src/static/images-static/uploads/macos-wireguard-010.png
  src/static/images-static/uploads/windows-10-wireguard-010.png
Labels: type: documentation

#174 IPv6 Support in Account Settings
  src/themes/ivpn-v3/assets/js/components/WireguardKey.vue
  src/themes/ivpn-v3/package.json
  src/themes/ivpn-v3/yarn.lock
Labels: type: task
