Repository ivpn/ivpn.net, pull requests merged in 2021-11, with the labels that each got.

#283 Add MultiHop port in Servers status page
  src/themes/ivpn-v3/assets/js/components/ServerList.vue
Labels: type: feature

#264 Update do-you-offer-a-kill-switch-or-vpn-firewall.md
  src/content/pages/knowledgebase/general/do-you-offer-a-kill-switch-or-vpn-firewall.md
Labels: type: documentation

#280 New teams pricing page
  src/content/pages/pricing-teams.md
  src/themes/ivpn-v3/assets/js/views/Prices.vue
  src/themes/ivpn-v3/assets/scss/components/price-box.scss
  src/themes/ivpn-v3/assets/scss/pages.scss
Labels: type: feature

#278 New blog post - Kill switch added to iOS app
  src/content/blog/kill-switch-and-wireguard-multi-hop-added-to-ivpn-for-ios.md
  src/content/pages/knowledgebase/ios/native-ios-kill-switch-known-issues.md
Labels: type: documentation

#291 Add silicon battery test blog post
  src/content/blog/battery-life-apple-silicon-build-ivpn-app.md
  src/static/images-static/uploads/silicon_tests.png
  src/static/images-static/uploads/silicon_thumb.png
Labels: type: documentation

#288 Show specific error message for 3D Secure failure
  src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
Labels: type: enhancement

#292 Update "Known issues with Native iOS Kill Switch" article
  src/content/pages/knowledgebase/ios/native-ios-kill-switch-known-issues.md
Labels: type: documentation

#301 Android release 2.8.1
  src/content/pages/apps-android.md
Labels: type: task
