Repository ivpn/ivpn.net, pull requests merged in 2021-04, with the labels that each got.

#136 Update position on ChromeOS support
  src/content/pages/knowledgebase/general/do-you-support-chromebook.md
Labels: type: documentation

#137 Add new help articles for Android
  src/content/pages/knowledgebase/android/developer-options-on-the-android-phone.md
  src/content/pages/knowledgebase/android/mock-location-option.md
  src/static/images-static/uploads/developer-options-on-the-android-phone-1.png
  src/static/images-static/uploads/mock-location-option-1.png
  src/static/images-static/uploads/mock-location-option-2.png
  src/static/images-static/uploads/mock-location-option-3.png
  src/themes/ivpn-v3/assets/scss/elements/img.scss
Labels: no_qa_required, type: task

#138 Desktop app updates/v3.3.7
  src/content/pages/apps-macos.md
  src/content/pages/apps-windows.md
Labels: no_qa_required, type: task

#139 Update Windows app screenshots
  src/content/pages/apps-windows.md
  src/static/images-static/uploads/apps/windows-app-3.3.7-dark.png
  src/static/images-static/uploads/apps/windows-app-3.3.7-dark@2x.png
  src/static/images-static/uploads/apps/windows-app-3.3.7-light.png
  src/static/images-static/uploads/apps/windows-app-3.3.7-light@2x.png
  src/static/images-static/uploads/apps/windows-app-dark.png
  src/static/images-static/uploads/apps/windows-app-dark@2x.png
  src/static/images-static/uploads/apps/windows-app-light.png
  src/static/images-static/uploads/apps/windows-app-light@2x.png
  src/static/images-static/uploads/windows_dark_mode.png
Labels: no_qa_required, type: task

#142 Update Linux app screenshots
  src/content/pages/apps-linux.md
  src/static/images-static/uploads/apps/linux-app-3.3.7-dark.png
  src/static/images-static/uploads/apps/linux-app-3.3.7-dark@2x.png
  src/static/images-static/uploads/apps/linux-app-3.3.7-light.png
  src/static/images-static/uploads/apps/linux-app-3.3.7-light@2x.png
  src/static/images-static/uploads/apps/linux-app-dark.png
  src/static/images-static/uploads/apps/linux-app-dark@2x.png
  src/static/images-static/uploads/apps/linux-app-light.png
  src/static/images-static/uploads/apps/linux-app-light@2x.png
Labels: no_qa_required, type: task

#143 Update mock-location-option.md
  src/content/pages/knowledgebase/android/mock-location-option.md
Labels: no_qa_required, type: task

#145 Android client v2.4.0
  src/content/pages/apps-android.md
Labels: type: task

#147 Update apps-android.md
  src/content/pages/apps-android.md
Labels: no_qa_required, type: task

#148 Update apps-windows.md
  src/content/pages/apps-windows.md
Labels: no_qa_required, type: task

#149 New Android IVPN client 2.4.1
  src/content/pages/apps-android.md
Labels: no_qa_required, type: task

#151 Desktop app updates/v3.3.10
  src/content/pages/apps-linux.md
  src/content/pages/apps-macos.md
  src/content/pages/apps-windows.md
Labels: type: task

#153 Update apps-linux.md
  src/content/pages/apps-linux.md
Labels: type: task

#150 Update windows-my-ip-address-doesnandsharp039t-change-when-connected-…
  src/content/pages/knowledgebase/windows/windows-my-ip-address-doesnandsharp039t-change-when-connected-why.md
Labels: type: documentation
