Repository ivpn/ivpn.net, pull requests merged in 2021-12, with the labels that each got.

#305 Update Braintree 3D Secure error handling
  src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
Labels: type: bug

#307 Column sorting on server status page works once, then cannot be sorted again
  src/themes/ivpn-v3/assets/js/components/ServerList.vue
Labels: type: bug

#309 Update: fix default RDP port
  src/content/pages/knowledgebase/windows/windows-how-to-establish-rdp-connection-to-a-computer-running-ivpn.md
Labels: priority: low, type: documentation

#310 Update: How to perform a VPN leak test
  src/content/pages/privacy-guides/how-to-perform-a-vpn-leak-test.md
Labels: type: documentation

#313 Update: Online Privacy Through OPSEC and Compartmentalization: Part 4
  src/content/pages/privacy-guides/online-privacy-through-opsec-and-compartmentalization-part-4.md
Labels: type: documentation

#315 Update: Linux repo commands, remove leading dollar sign for easy copy…
  src/content/pages/apps-linux.md
Labels: type: documentation

#314 Update: Hardcore Mode domains
  src/content/pages/antitracker.md
  src/content/pages/knowledgebase/general/antitracker-faq.md
  src/content/pages/knowledgebase/linux/linux-webpages-do-not-load-or-dns-leaks-when-connecting-via-networkmanager.md
  src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
  src/content/pages/setup/android-wireguard.md
  src/content/pages/setup/ios-wireguard.md
  src/content/pages/setup/linux-wireguard-netman.md
  src/content/pages/setup/router/openwrt-wireguard.md
  src/content/pages/setup/router/openwrt.md
  src/content/pages/setup/router/opnsense-wireguard.md
  src/content/pages/setup/router/opnsense.md
  src/content/pages/setup/router/pfsense-wireguard.md
Labels: type: documentation
