Repository ivpn/ivpn.net, pull requests merged in 2021-05, with the labels that each got.

#155 Update Debian-like install instructions; apt-key is deprecated
  src/content/pages/apps-linux.md
  src/themes/ivpn-v3/assets/scss/elements/pre.scss
Labels: type: documentation

#159 Fix code block style issue
  src/content/pages/knowledgebase/linux/linux-how-do-i-prevent-vpn-leaks-using-iptables.md
  src/themes/ivpn-v3/assets/scss/elements/pre.scss
Labels: type: bug

#162 Task/edit antitracker faq
  src/content/pages/knowledgebase/general/antitracker-faq.md
  src/content/pages/setup/linux-wireguard-netman.md
Labels: type: documentation

#167 Apps URL not updated in the main menu
  src/themes/ivpn-v3/assets/js/menu.js
Labels: type: bug

#170 Add macOS KB article for launch at login
  src/content/pages/knowledgebase/macos/macos-launch-at-login-is-not-available.md
Labels: type: documentation

#165 Update GitHub repo URL
  src/content/blog/new-ivpn-linux-app-with-gui-now-available.md
  src/content/pages/apps-ios.md
  src/content/pages/apps-linux.md
  src/content/pages/apps-macos.md
  src/content/pages/apps-windows.md
Labels: type: task
