Repository ivpn/ivpn.net, pull requests merged in 2021-09, with the labels that each got.

#236 Add link to official WireGuard client download page
  src/content/pages/setup/windows-10-wireguard.md
Labels: type: documentation

#241 Create extending-two-factor-authentication-to-ivpn-apps.md
  src/content/blog/extending-two-factor-authentication-to-ivpn-apps.md
Labels: type: documentation

#235 Add warning about apps when enabling 2FA in the client area
  src/themes/ivpn-v3/assets/js/views/Account/Settings.vue
  src/themes/ivpn-v3/assets/js/views/Account/Settings/Authentication.vue
Labels: type: task

#240 Upgrade dependencies
  src/themes/ivpn-v3/package.json
  src/themes/ivpn-v3/yarn.lock
Labels: type: task

#242 Task/edit case sensitive
  src/content/pages/apps-android.md
  src/content/pages/setup/android-featvpn.md
  src/content/pages/setup/android-ipsec-with-ikev2.md
  src/content/pages/setup/android-openvpn-for-android.md
  src/content/pages/setup/ipad-ipsec-ikev2.md
  src/content/pages/setup/ipad-openvpn-connect.md
  src/content/pages/setup/iphone-ipsec-ikev2.md
  src/content/pages/setup/iphone-openvpn-connect.md
  src/content/pages/setup/linux-ipsec-with-ikev2.md
  src/content/pages/setup/linux-netman.md
  src/content/pages/setup/linux-terminal.md
  src/content/pages/setup/macos-ipsec-with-ikev2.md
  src/content/pages/setup/macos-openvpn-tunnelblick.md
  src/content/pages/setup/nas/qnap.md
  src/content/pages/setup/nas/synology-6.md
  src/content/pages/setup/router/asuswrt.md
  src/content/pages/setup/router/ddwrt-auto.md
  src/content/pages/setup/router/ddwrt-manual.md
  src/content/pages/setup/router/openwrt.md
  src/content/pages/setup/router/opnsense.md
  src/content/pages/setup/router/pfsense.md
  src/content/pages/setup/router/tomato-manual.md
  src/content/pages/setup/windows-10-ipsec-with-ikev2.md
  src/content/pages/setup/windows-10-openvpn-community.md
  src/content/pages/setup/windows-8-openvpn-community.md
  src/static/images-static/uploads/install-featvpn-android-010-281x500.png
  src/static/images-static/uploads/install-featvpn-android-020-281x500.png
  src/static/images-static/uploads/install-featvpn-android-030-281x500.png
  src/static/images-static/uploads/install-featvpn-android-040-281x500.png
  src/static/images-static/uploads/install-featvpn-android-050-281x500.png
  src/static/images-static/uploads/install-featvpn-android-070-281x500.png
  src/static/images-static/uploads/install-featvpn-android-080-281x500.png
  src/static/images-static/uploads/install-featvpn-android-090-281x500.png
  src/static/images-static/uploads/install-featvpn-android-100-281x500.png
Labels: type: documentation

#243 KB: Add split tunnel limitations article
  src/content/pages/knowledgebase/general/split-tunnel-uses-and-limitations.md
Labels: type: documentation

#246 New blog - Introducing split tunnelling to IVPN for Windows
  src/content/blog/introducing-split-tunnelling-to-ivpn-for-windows.md
  src/static/images-static/uploads/split.png
Labels: type: documentation

#247 Add Split tunneling in the list of features
  src/content/pages/apps-windows.md
Labels: type: documentation

#238 Server status page update
  src/static/images-static/arrow-blue.svg
  src/static/images-static/arrow-gray.svg
  src/themes/ivpn-v3/assets/js/components/ServerList.vue
  src/themes/ivpn-v3/assets/scss/components/select.scss
  src/themes/ivpn-v3/assets/scss/components/servers.scss
  src/themes/ivpn-v3/assets/scss/config/colors.scss
  src/themes/ivpn-v3/assets/scss/config/grid.scss
  src/themes/ivpn-v3/assets/scss/pages.scss
  src/themes/ivpn-v3/layouts/pages/servers.html
Labels: type: bug, type: enhancement

#253 Server status page: Expanded server collapses with a click making copying the WG key difficult
  src/themes/ivpn-v3/assets/scss/components/servers.scss
Labels: type: bug

#256 Small UI update for Manifesto page
  src/content/pages/manifesto.md
  src/themes/ivpn-v3/assets/scss/base.scss
  src/themes/ivpn-v3/assets/scss/components/eof.scss
  src/themes/ivpn-v3/assets/scss/mixins/blink-me.scss
  src/themes/ivpn-v3/assets/scss/pages.scss
Labels: no_qa_required, type: task

#254 Remove theme switcher on the Home page
  src/content/pages/home.md
  src/themes/ivpn-v3/assets/scss/components/team.scss
  src/themes/ivpn-v3/layouts/partials/blocks/heading_text_two_cta_two_column.html
  src/themes/ivpn-v3/layouts/partials/blocks/usps_three_column_home.html
Labels: no_qa_required, type: task

#255 Servers status page update
  src/themes/ivpn-v3/assets/js/components/ServerList.vue
  src/themes/ivpn-v3/assets/scss/components/select.scss
  src/themes/ivpn-v3/assets/scss/components/servers.scss
  src/themes/ivpn-v3/assets/scss/config/grid.scss
Labels: type: task
