Repository ivpn/ivpn.net, pull requests merged in 2021-02, with the labels that each got.

#79 Fixes for OPNSense setup guide and IPv6 KB article
  src/content/pages/knowledgebase/general/do-you-offer-ipv6.md
  src/content/pages/setup/router/opnsense.md
  src/static/images-static/uploads/opns-wg-3-5-edit-local-interface.png
Labels: type: documentation

#78 Update home-app-dark.png illustration
  src/static/images-static/uploads/home-app-dark-2x.png
  src/static/images-static/uploads/home-app-dark.png
Labels: type: bug

#77 Update pricing page redirect
  nginx.conf
Labels: type: bug

#76 Fix URL in /privacy-guides/advanced-privacy-and-anonymity-part-3
  src/content/pages/privacy-guides/advanced-privacy-and-anonymity-part-3.md
Labels: type: bug

#82 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: no_qa_required, type: documentation

#90 Fix typo in advanced privacy guide part 7
  src/content/pages/privacy-guides/advanced-privacy-and-anonymity-part-7.md
Labels: type: documentation

#92 Make the QR code on the account section bigger
  src/themes/ivpn-v3/assets/js/components/AccountInfo.vue
Labels: type: task

#91 Cutoff in the Home screen on small devices
  src/themes/ivpn-v3/assets/scss/elements/headings.scss
Labels: type: bug

#94 Update Custom DNS article for new app design
  src/content/pages/knowledgebase/general/custom-dns.md
Labels: type: documentation

#96 Fix 'kill switch' phrase; minor consistency updates
  src/content/pages/knowledgebase/general/do-you-offer-a-kill-switch-or-vpn-firewall.md
  src/content/pages/knowledgebase/linux/linux-kill-switch-using-the-uncomplicated-firewall-ufw.md
  src/content/pages/knowledgebase/linux/linux-wireguard-kill-switch.md
  src/content/pages/knowledgebase/linux/managing-the-ivpn-linux-client-at-system-boot.md
  src/content/pages/knowledgebase/troubleshooting/how-to-submit-vpn-diagnostic-logs-to-ivpn.md
  src/content/pages/setup/router/opnsense.md
  src/content/pages/setup/router/pfsense.md
Labels: type: documentation

#98 Task/pf sense wire guard setup guide
  src/content/pages/setup/router/opnsense.md
  src/content/pages/setup/router/pfsense-wireguard.md
  src/content/pages/setup/router/pfsense.md
  src/static/images-static/uploads/pf-wg-10-peer.png
  src/static/images-static/uploads/pf-wg-20-fw-nat-outbound.png
  src/static/images-static/uploads/pf-wg-30-fw-rules-lan.png
  src/static/images-static/uploads/pf-wg-35-routing.png
  src/static/images-static/uploads/pf-wg-40-dns.png
  src/static/images-static/uploads/pf-wg-50-killswitch.png
Labels: type: documentation

#105 Update minor details in the pfSense WireGuard guide
  src/content/pages/setup/router/pfsense-wireguard.md
  src/content/pages/setup/router/pfsense.md
Labels: type: documentation

#106 Update how-do-i-activate-port-forwarding.md
  src/content/pages/knowledgebase/general/how-do-i-activate-port-forwarding.md
Labels: type: documentation
