Repository ivpn/ivpn.net, pull requests merged in 2021-01, with the labels that each got.

#49 Broken images in certain blog post entries
  src/static/images-static/ivpn-placeholder.svg
  src/themes/ivpn-v3/assets/scss/components/blog.scss
Labels: bug

#50 Publish RSS feed for blog
  src/config/_default/config.toml
Labels: enhancement

#51 UI issue on 2-Factor Authentication popup
  src/themes/ivpn-v3/assets/js/components/popups/TotpEnable.vue
Labels: bug

#61 Task/ddwrt wireguard update
  src/content/pages/setup/router/ddwrt-wireguard.md
  src/static/images-static/uploads/install-openvpn-ddwrt-wireguard-020.png
Labels: documentation

#68 TCP Option
  src/content/pages/apps-android.md
  src/content/pages/apps-ios.md
  src/content/pages/apps-linux.md
  src/content/pages/apps-macos.md
  src/content/pages/apps-windows.md
  src/content/pages/setup/linux-terminal.md
Labels: documentation

#70 Update router killswitch KB article
  src/content/pages/knowledgebase/routers/how-to-enable-a-andsharp039kill-switchandsharp039-in-my-dd-wrtortomato-router.md
Labels: documentation
