Repository ivpn/ivpn.net, pull requests merged in 2022-03, with the labels that each got.

#349 Update header template
  src/themes/ivpn-v3/assets/scss/components/heading.scss
  src/themes/ivpn-v3/layouts/partials/header.html
Labels: type: task

#346 Upgrade dependencies in package.json
  src/themes/ivpn-v3/package.json
  src/themes/ivpn-v3/yarn.lock
Labels: type: build/ci, type: task

#338 OpenVPN and WireGuard configuration pages
  src/content/pages/openvpn-configuration.md
  src/themes/ivpn-v3/assets/js/api/api.js
  src/themes/ivpn-v3/assets/js/components/AccountMenu.vue
  src/themes/ivpn-v3/assets/js/components/OpenvpnConfig.vue
  src/themes/ivpn-v3/assets/js/components/icons/os/linux2.vue
  src/themes/ivpn-v3/assets/js/openvpn-config.js
  src/themes/ivpn-v3/assets/js/router/index.js
  src/themes/ivpn-v3/assets/js/styles/vpn-configuration.scss
  src/themes/ivpn-v3/assets/js/views/Account/Wireguard.vue
  src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
  src/themes/ivpn-v3/assets/js/wireguard.js
  src/themes/ivpn-v3/layouts/pages/openvpn-config.html
  src/themes/ivpn-v3/package.json
  src/themes/ivpn-v3/webpack.mix.js
  src/themes/ivpn-v3/yarn.lock
Labels: type: feature

#352 Support UA page
  src/content/pages/supportua-ru.md
  src/content/pages/supportua.md
  src/themes/ivpn-v3/assets/js/api/api.js
  src/themes/ivpn-v3/assets/js/components/SupportUA.vue
  src/themes/ivpn-v3/assets/js/store/index.js
  src/themes/ivpn-v3/assets/js/store/module_contact.js
  src/themes/ivpn-v3/assets/js/supportua.js
  src/themes/ivpn-v3/assets/scss/elements/input.scss
  src/themes/ivpn-v3/layouts/_default/baseof.html
  src/themes/ivpn-v3/layouts/pages/supportua-ru.html
  src/themes/ivpn-v3/layouts/pages/supportua.html
  src/themes/ivpn-v3/webpack.mix.js
Labels: type: feature

#357 Config generators kB/Setup guides update
  src/content/pages/apps-android.md
  src/content/pages/apps-ios.md
  src/content/pages/apps-linux-legacy.md
  src/content/pages/apps-linux.md
  src/content/pages/apps-macos.md
  src/content/pages/apps-windows.md
  src/content/pages/knowledgebase/general/do-you-offer-openvpn-config-files-for-tcp-connections.md
  src/content/pages/knowledgebase/general/do-you-offer-openvpn-wireguard-config-files.md
  src/content/pages/knowledgebase/general/how-can-i-connect-to-the-multihop-network.md
  src/content/pages/knowledgebase/general/tcp-and-udp-connections.md
  src/content/pages/knowledgebase/general/wireguard-faq.md
  src/content/pages/knowledgebase/linux/linux-cannot-import-ovpn-config-file.md
  src/content/pages/knowledgebase/linux/linux-how-can-i-circumvent-vpn-censorship-by-masking-the-vpn-traffic.md
  src/content/pages/knowledgebase/mp/connecting-to-ivpn-on-amazon-fire-tv.md
  src/content/pages/knowledgebase/mp/how-to-use-ivpn-on-kodi-media-player.md
  src/content/pages/knowledgebase/mp/is-ivpn-compatible-with-appletv.md
  src/content/pages/privacy-guides/raspberry-pi-2-ivpn-gateway.md
  src/content/pages/setup/android-openvpn-for-android.md
  src/content/pages/setup/android-wireguard.md
  src/content/pages/setup/ios-openvpn-connect.md
  src/content/pages/setup/ios-wireguard.md
  src/content/pages/setup/linux-netman.md
  src/content/pages/setup/linux-terminal.md
  src/content/pages/setup/macos-openvpn-tunnelblick.md
  src/content/pages/setup/macos-wireguard.md
  src/content/pages/setup/nas/qnap.md
  src/content/pages/setup/nas/synology-6.md
  src/content/pages/setup/router/asuswrt.md
  src/content/pages/setup/router/openwrt.md
  src/content/pages/setup/router/opnsense.md
  src/content/pages/setup/router/pfsense.md
  src/content/pages/setup/windows-10-openvpn-community.md
  src/content/pages/setup/windows-10-wireguard.md
  src/content/pages/setup/windows-8-openvpn-community.md
  src/content/pages/wireguard-vpn.md
  src/static/images-static/uploads/connection-status-tool.png
Labels: type: documentation

#355 WireGuard configuration in the Account settings
  src/themes/ivpn-v3/assets/js/styles/vpn-configuration.scss
  src/themes/ivpn-v3/assets/js/views/Account/Wireguard.vue
  src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
Labels: type: content

#358 Update BraintreeCc.vue template
  src/themes/ivpn-v3/assets/js/components/BraintreeCc.vue
Labels: type: task, type: content

#359 Add key comment in WireGuard configuration
  src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
Labels: type: task
