Repository ivpn/ivpn.net, pull requests merged in 2022-06, with the labels that each got.

#391 Start using Conventional Commits specification
  .github/CONTRIBUTING.md
Labels: type: documentation

#393 Spelling correction
  src/themes/ivpn-v3/layouts/partials/footer.html
Labels: type: documentation

#394 Apps/update/android/v2.8.3
  src/content/pages/apps-android.md
Labels: type: task

#395 Update iOS app screenshot
  src/static/images-static/uploads/apps/ios-app-dark.png
  src/static/images-static/uploads/apps/ios-app-dark@2x.png
Labels: type: content
