Repository ivpn/ivpn.net, pull requests merged in 2022-02, with the labels that each got.

#336 Add manifest-example.json
  src/themes/ivpn-v3/data/manifest-example.json
Labels: type: build/ci

#337 Task/update advanced privacy and anonymity part 2
  src/content/pages/privacy-guides/advanced-privacy-and-anonymity-part-2.md
  src/content/pages/privacy-guides/onion-ssh-hosts-for-login-chaining.md
Labels: type: documentation

#331 Added Monero to the payment options page
  src/content/pages/pricing-teams.md
Labels: type: content

#339 cVPN vs. dVPN comparison privacy guide
  src/content/pages/privacy-guides/comparing-dvpns-centralized-vpns-privacy-protection.md
  src/content/pages/privacy-guides/how-to-verify-physical-locations-of-internet-servers.md
Labels: type: content

#340 Add apple-app-site-association file
  src/static/ .well-known/apple-app-site-association
Labels: type: task

#341 WireGuard Port Forwarding release
  src/content/blog/wireguard-port-forwarding-enabled.md
  src/themes/ivpn-v3/assets/js/views/Account/PortForwarding.vue
Labels: type: content

#344 Add print button in Cash payment page
  src/themes/ivpn-v3/assets/js/views/Account/AddFunds/Cash.vue
Labels: type: feature
