Repository ivpn/ivpn.net, pull requests merged in 2022-07, with the labels that each got.

#403 Link to submitting VPN diagnostics logs page sends you to a 404
  src/content/pages/knowledgebase/troubleshooting/my-vpn-is-connected-but-i-cannot-browse-the-internet-why.md
Labels: type: content

#410 Update verify-x509-name in OpenVPN configurator
  src/themes/ivpn-v3/assets/js/components/OpenvpnConfig.vue
Labels: type: task

#320 Update: AntiTracker blog post, domains
  src/content/blog/2019-06-11-block-ads-and-beat-data-surveillance-with-ivpns-antitracker.md
Labels: type: documentation

#412 Make server load format consistent on /status page
  src/themes/ivpn-v3/assets/js/components/ServerList.vue
Labels: type: task

#416 Create ci-build.yml
  .github/workflows/ci-build.yml
Labels: type: build/ci

#417 Update home illustration
  src/content/pages/home.md
  src/static/images-static/uploads/home-hero-2x.png
  src/static/images-static/uploads/home-hero-dark.png
  src/static/images-static/uploads/home-hero-dark@2x.png
  src/static/images-static/uploads/home-hero.png
  src/static/images-static/uploads/ivpn-home-dark.png
  src/static/images-static/uploads/ivpn-home-dark@2x.png
  src/static/images-static/uploads/ivpn-home.png
  src/static/images-static/uploads/ivpn-home@2x.png
Labels: type: bug

#405 Add KB article: SOCKS5 Proxy Service
  src/content/pages/knowledgebase/general/socks5-proxy-service.md
  src/static/images-static/uploads/sock5-macos.png
  src/static/images-static/uploads/socks5-edge.png
  src/static/images-static/uploads/socks5-firefox.png
Labels: type: documentation

#400 Add Socks5 information on servers status page
  src/themes/ivpn-v3/assets/js/components/ServerList.vue
Labels: type: feature

#420 Update: Include snap info
  src/content/pages/apps-linux.md
Labels: type: documentation

#421 Update Linux app page
  src/content/pages/apps-linux.md
  src/static/images-static/uploads/snap-store-black@2x.png
  src/static/images-static/uploads/snap-store-white@2x.png
  src/themes/ivpn-v3/assets/scss/elements/pre.scss
Labels: type: content

#422 docs(typo): replace aas with as
  src/content/pages/knowledgebase/troubleshooting/my-real-location-is-detected-when-connected-to-vpn-how-to-disable-geolocation.md
Labels: type: content

#424 Make dark scroll bar in dark theme in Chromium-based browsers
  src/themes/ivpn-v3/assets/scss/elements/body.scss
Labels: type: enhancement
