Repository ivpn/ivpn.net, pull requests merged in 2023-04, with the labels that each got.

#508 Update dependencies
  src/themes/ivpn-v3/package.json
  src/themes/ivpn-v3/yarn.lock
Labels: dependencies

#510 Update apps-android.md
  src/content/pages/apps-android.md
Labels: type: content

#511 Update styles in ThankYou.vue
  src/themes/ivpn-v3/assets/js/views/Account/ThankYou.vue
Labels: type: bug

#512 Task/add kb fw exceptions
  src/content/pages/knowledgebase/general/firewall-exceptions.md
Labels: type: documentation

#514 Update apps-android.md page
  src/content/pages/apps-android.md
Labels: type: content

#516 Add a blue strip promo to specific pages on the website
  src/themes/ivpn-v3/layouts/partials/header.html
Labels: type: feature
