Repository ivpn/ivpn.net, pull requests merged in 2023-08, with the labels that each got.

#661 Various KnowledgeBase changes
  src/content/pages/knowledgebase/billing/how-can-i-pay-with-cash.md
  src/content/pages/knowledgebase/billing/i-paid-with-paypal-but-my-account-is-still-pending-why.md
  src/content/pages/knowledgebase/billing/paid-with-paypal-using-echeck-but-ivpn-account-is-still-in-pendingorsuspended-state-why.md
  src/content/pages/knowledgebase/billing/voucher-cards-faq.md
  src/content/pages/knowledgebase/general/antitracker-faq.md
  src/content/pages/knowledgebase/general/antivirus-detects-malware-in-the-ivpn-installer-why.md
  src/content/pages/knowledgebase/general/do-you-allow-smtp-email-whilst-connected-to-ivpn.md
  src/content/pages/knowledgebase/general/do-you-offer-a-kill-switch-or-vpn-firewall.md
  src/content/pages/knowledgebase/general/do-you-offer-dedicated-or-static-ip-addresses.md
  src/content/pages/knowledgebase/general/do-you-offer-two-factor-authentication.md
  src/content/pages/knowledgebase/general/do-you-support-blackberry.md
  src/content/pages/knowledgebase/general/firewall-exceptions.md
  src/content/pages/knowledgebase/general/how-many-ips-do-you-have-in-total-or-per-server.md
  src/content/pages/knowledgebase/general/my-ip-is-being-leaked-by-webrtc-how-do-i-disable-it.md
  src/content/pages/knowledgebase/general/socks5-proxy-service.md
  src/content/pages/knowledgebase/general/split-tunnel-uses-and-limitations.md
  src/content/pages/knowledgebase/general/what-makes-ivpn-so-fast.md
  src/content/pages/knowledgebase/general/why-is-the-location-of-the-server-not-accurate.md
  src/content/pages/knowledgebase/general/wireguard-faq.md
  src/content/pages/knowledgebase/macos/macos-how-do-i-completely-uninstall-or-remove-the-ivpn-application.md
  src/content/pages/knowledgebase/macos/tunnelblick-how-do-i-edit-the-openvpn-config-file.md
  src/content/pages/knowledgebase/macos/tunnelblick-how-to-submit-diagnostic-data-to-ivpn.md
  src/content/pages/knowledgebase/macos/tunnelblick-password-or-authentication-failure.md
  src/content/pages/knowledgebase/privacy/what-happens-if-laws-change-forcing-ivpn-to-compromise-their-customers-privacy.md
  src/content/pages/knowledgebase/privacy/what-information-do-you-collect-and-store-when-i-signup-for-your-service.md
  src/content/pages/knowledgebase/privacy/what-information-is-collected-and-stored-about-all-visitors-to-your-website.md
  src/content/pages/knowledgebase/routers/dd-wrt-how-do-i-exclude-hosts-or-bypass-vpn-tunnel.md
  src/content/pages/knowledgebase/troubleshooting/how-can-i-reset-my-dns-settings.md
  src/content/pages/knowledgebase/troubleshooting/how-do-i-change-the-port-or-protocol-used-to-connect.md
  src/content/pages/knowledgebase/troubleshooting/how-do-i-clear-or-flush-my-dns-cache.md
  src/content/pages/knowledgebase/troubleshooting/how-do-i-connect-to-the-vpn-from-a-remote-server.md
  src/content/pages/knowledgebase/troubleshooting/how-do-i-verify-the-location-of-server.md
  src/content/pages/knowledgebase/troubleshooting/how-to-disable-enhanced-app-authentication-eaa.md
  src/content/pages/knowledgebase/troubleshooting/how-to-submit-vpn-diagnostic-logs-to-ivpn.md
  src/content/pages/knowledgebase/troubleshooting/i-cannot-access-devices-on-my-local-network-why.md
  src/content/pages/knowledgebase/troubleshooting/i-cannot-connect-to-the-vpn-what-can-i-do.md
  src/content/pages/knowledgebase/troubleshooting/i-cant-connect-from-china-or-vietnam-or-iran-etc-how-do-i-enable-obfsproxy.md
  src/content/pages/knowledgebase/troubleshooting/i-lose-internet-connection-when-i-disconnect-from-ivpn-why.md
  src/content/pages/knowledgebase/troubleshooting/my-vpn-connection-is-randomly-disconnecting-what-can-i-do.md
  src/content/pages/knowledgebase/troubleshooting/my-vpn-is-slow-what-can-i-do-to-make-it-faster.md
  src/content/pages/knowledgebase/troubleshooting/the-battery-on-my-phone-drains-too-fast-while-using-ivpn-why.md
  src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
  src/content/pages/knowledgebase/windows/windows-all-tap-win32-adapters-in-use-error.md
  src/content/pages/knowledgebase/windows/windows-how-do-i-configure-openvpn-to-start-automatically.md
Labels: type: documentation, type: content

#664 Android v2.10.0 release
  src/content/pages/apps-android.md
Labels: type: task

#590 adding post-quantum resistance kb articles
  src/content/pages/knowledgebase/general/quantum-resistance-faq.md
  src/content/pages/knowledgebase/general/quantum-resistant-vpn-connections.md
  src/static/images-static/uploads/desktop-verify-quantum.png
  src/static/images-static/uploads/mobile-verify-quantum.png
  src/static/images-static/uploads/quantum-resistance-1.png
  src/static/images-static/uploads/quantum-resistance-2.png
  src/static/images-static/uploads/quantum-resistance-3.png
Labels: type: content

#673 Remove port forwarding references on upgrade product area
  src/themes/ivpn-v3/assets/js/views/Account/ChangeProduct/ChangeProduct.vue
Labels: priority: low, type: feature

#675 Android v2.10.1 release
  src/content/pages/apps-android.md
Labels: type: task

#674 KB update: AntiTracker mentions part 1
  src/content/pages/antitracker.md
  src/content/pages/knowledgebase/general/antitracker-faq.md
  src/content/pages/knowledgebase/general/antitracker-plus-lists-explained.md
  src/content/pages/knowledgebase/troubleshooting/what-is-the-ip-address-of-your-dns-servers.md
Labels: type: documentation

#678 Update pfSense OpenVPN router guide
  src/content/pages/setup/router/pfsense.md
  src/static/images-static/uploads/install-openvpn-pfsense-2.4.3-010.png
  src/static/images-static/uploads/install-openvpn-pfsense-2.4.3-020.png
  src/static/images-static/uploads/install-openvpn-pfsense-2.4.3-030.png
  src/static/images-static/uploads/install-openvpn-pfsense-2.4.3-040.png
  src/static/images-static/uploads/install-pfsense-openvpn-2.7.0-010.png
  src/static/images-static/uploads/install-pfsense-openvpn-2.7.0-020.png
  src/static/images-static/uploads/install-pfsense-openvpn-2.7.0-030.png
  src/static/images-static/uploads/install-pfsense-openvpn-2.7.0-040.png
  src/static/images-static/uploads/install-pfsense-openvpn-2.7.0-050.png
Labels: type: documentation
