Repository ivpn/ivpn.net, pull requests merged in 2023-11, with the labels that each got.

#710 Add SOCKS5 proxy port number to Server Status page
  src/themes/ivpn-v3/assets/js/components/ServerList.vue
Labels: type: task

#702 V2Ray on iOS KB article
  src/content/pages/knowledgebase/ios/v2ray.md
  src/themes/ivpn-v3/layouts/pages/help-details.html
  src/themes/ivpn-v3/layouts/pages/help.html
Labels: type: content

#712 Make the "Account ID" login form the default one
  src/themes/ivpn-v3/assets/js/views/Login.vue
Labels: type: task

#714 Update apps-windows.md
  src/content/pages/apps-windows.md
Labels: type: content

#715 Error when git clone on Windows 10 and some files are not reflected
  .gitignore
  src/content/.DS_Store
  src/content/pages/knowledgebase/.DS_Store
  src/content/pages/knowledgebase/android/what-permissions-does-your-app-require-and-why.md
Labels: type: bug

#717 Login validation does not ignore spaces before and/or after the account ID/Email
  src/themes/ivpn-v3/assets/js/views/Login.vue
Labels: type: bug

#719 Edit: update AT+ lists
  src/content/pages/knowledgebase/general/antitracker-plus-lists-explained.md
Labels: type: documentation

#720 Improve wireguard config generator
  src/themes/ivpn-v3/assets/js/api/api.js
  src/themes/ivpn-v3/assets/js/styles/vpn-configuration.scss
  src/themes/ivpn-v3/assets/js/views/Account/WireguardConfig.vue
Labels: type: feature
