Repository ivpn/ivpn.net, pull requests merged in 2024-04, with the labels that each got.

#767 task:Remove livechat
  src/themes/ivpn-v3/layouts/partials/footer.html
Labels: type: task

#769 Bugfix/scroll on payment
  src/themes/ivpn-v3/assets/js/router/index.js
Labels: priority: high, type: bug

#745 Update Hugo and nodeJS
  Dockerfile
  src/config/_default/config.toml
  src/themes/ivpn-v3/assets/scss/components/highlight.scss
  src/themes/ivpn-v3/layouts/blog/single.html
  src/themes/ivpn-v3/layouts/pages/guides.html
  src/themes/ivpn-v3/layouts/pages/help-details.html
  src/themes/ivpn-v3/layouts/pages/help.html
  src/themes/ivpn-v3/layouts/pages/setup-article.html
  src/themes/ivpn-v3/layouts/pages/setup-list.html
  src/themes/ivpn-v3/layouts/partials/blog-article.html
  src/themes/ivpn-v3/layouts/partials/blog-categories.html
  src/themes/ivpn-v3/layouts/partials/blog-side-bar.html
Labels: priority: medium, dependencies
