Repository ivpn/ivpn.net, pull requests merged in 2024-08, with the labels that each got.

#811 Android v2.10.9 release
  src/content/en/pages/apps-android.md
  src/content/es/pages/apps-android.md
Labels: type: task

#812 Remove free voucher bluestrip
  src/themes/ivpn-v3/assets/js/menu.js
  src/themes/ivpn-v3/assets/js/store/module_auth.js
  src/themes/ivpn-v3/layouts/partials/header.html
Labels: priority: high

#814 Android v2.10.10 release
  src/content/en/pages/apps-android.md
  src/content/es/pages/apps-android.md
Labels: type: task

#816 [docs] Correct wording from `extremly` to `extremely`.
  src/content/en/pages/knowledgebase/general/antitracker-plus-lists-explained.md
Labels: type: content
