Repository ivpn/ivpn.net, pull requests merged in 2024-10, with the labels that each got.

#830 Task/add lnurlp url
  nginx.conf
  src/static/.well-known/lnurlp
Labels: priority: high, type: task

#834 fix: Server Status page obfs4 key label, EN and ES
  src/themes/ivpn-v3/locales/en.json
  src/themes/ivpn-v3/locales/es.json
Labels: type: bug

#835 docs: Add KB article: OpenWrt + obfs4proxy + OpenVPN
  src/content/en/pages/knowledgebase/routers/openwrt-obfs3-and-obfs4-obfuscation-with-obfsproxy-and-openvpn.md
  src/content/en/pages/setup/router/openwrt.md
Labels: type: documentation
