Repository ivpn/ivpn.net, pull requests merged in 2025-02, with the labels that each got.

#857 Blog post
  src/content/en/blog/key-rotation-issue-fix-in-ivpn-ios-app.md
Labels: type: content

#861 Android v2.10.12 release
  src/content/en/pages/apps-android.md
  src/content/es/pages/apps-android.md
Labels: type: task

#862 Fix typo: remove extra 'the'
  src/content/en/pages/pptp-vs-ipsec-ikev2-vs-openvpn-vs-wireguard.md
Labels: priority: low, type: documentation
